version: "3.2"

services:

  nucleus:
    image: elementaryrobotics/nucleus
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
    command: ./launch.sh

  record:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
      - ".:/code"
    depends_on:
      - "nucleus"
    environment:
      - "GRAPHICS=1"

volumes:
  shared:
    driver_opts:
      type: tmpfs
      device: tmpfs
