version: "3.2"

services:

  nucleus:
    image: elementaryrobotics/nucleus
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
    command: ./launch.sh

  robot:
    image: elementaryrobotics/element-robot
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
    command: launch_sim.sh

  record:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
      - ".:/code"
      - ".:/recordings"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    depends_on:
      - "nucleus"
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1"
    command: tail -f /dev/null

volumes:
  shared:
    driver_opts:
      type: tmpfs
      device: tmpfs
