version: 2.1

orbs:
  atom: elementaryrobotics/atom@0.0.1

jobs:
  build:
    executor: atom/build-classic
    environment:
      DOCKER_COMPOSE_SERVICE_NAME: record
    steps:
      - checkout
      - atom/docker_login
      - atom/build_and_launch:
          file: docker-compose.yml
          service: ${DOCKER_COMPOSE_SERVICE_NAME}
      - atom/store_image

workflows:
  version: 2
  build-all:
    jobs:
      - build
      - atom/deploy-master:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - atom/deploy-dev:
          requires:
            - build
          filters:
            branches:
              ignore:
                - master
